services:
  - type: web
    name: td-phone-backend
    env: docker
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
