spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/database_test}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

# Max file size (10MB)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=0

# Path to the image storage directory.
# Can be an absolute path e.g., C:/Users/user/images
# Or a relative path from where the application is run, e.g., image
# The repository already contains the 'image' folder at the project root.
app.image-storage-path=image
